### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by SonikBroom** [FWDekker/fo4vr-modlist#20]
Hello, I am having an issue where the game crashes on startup. I have run it through f4se with mo2, it doesn't work. I have tried running just f4se, doesn't work. even base game, it does not work. I launch the executable and get the error message The application was unable to start correctly (0xc0000142).

Luckily, after a lot of troubleshooting and bashing my head against the wall, I finally found the root of this issue (I think). It seems that the problem was xSE Plugin Preloader, as if I delete the IpHlpAPI.dll, the game actually boots into a vr window. I don't really understand how to fix it though, as I am very new to this stuff and don't know what I need to change in the config. If anyone can help that would be greatly appreciated!

**Comment by SonikBroom** [comment]
I found the logs, which might might help. I can't find where in the config I specify the original library path.
[xSE PluginPreloader.log](https://github.com/FWDekker/fo4vr-modlist/files/15448563/xSE.PluginPreloader.log)

**Comment by FWDekker** [comment]
Some quick suggestions I can think of from the top off my head:

1. You shouldn't need to edit paths in the config. If you've changed anything, I suggest you revert it to the original before continuing.
2. Note that the preloader requires the C++ redistributables. There's a small chance you're missing those. There's a download link in Section 2.2.
3. [The mod page for the preloader](https://www.nexusmods.com/fallout4/mods/33946) describes a potential fix, which might work for you. Try it out.
4. The logs mention some errors about being unable to find F4SE. Are you sure you've installed F4SEVR correctly? Section 4.1 of the guide explains how you can verify this. And are you sure you're launching F4SEVR through MO2? This is also explained in Section 4.1. Even if you followed them initially, go through these checks again, because this seems like a likely cause for your errors.

**Comment by FWDekker** [comment]
Hi @SonikBroom! Were you able to try out my troubleshooting tips?

**Comment by SonikBroom** [comment]
So sorry, I was busy and forgot about this. I do have f4se vr installed correctly (i think) as pictured below
![f4seisinstalled](https://github.com/FWDekker/fo4vr-modlist/assets/95891178/a72d9420-1a03-42b7-a36b-e7fb6065fa38)

I have C++ redistributables, which I have even tried updating or reinstalling.

I tried the fix on the page, I used on thread attach, and on process attach, didnt fix it, but the exe does open now, i dont get the error. when I run it with f4se through mo2, the fo4vr exe opens a window, in vr its a black screen, after a little bit though it closes

**Comment by SonikBroom** [comment]
This is what the log looks like now
[xSE PluginPreloader.log](https://github.com/user-attachments/files/15522818/xSE.PluginPreloader.log)

**Comment by SonikBroom** [comment]
I just looked around, and I found its generating crash logs now. here is my most recent one from runniing through mo2
[crash-2024-06-01-18-08-11.log](https://github.com/user-attachments/files/15522841/crash-2024-06-01-18-08-11.log)

**Comment by SonikBroom** [comment]
I just added the dlc files HUGE PROGRESS! I now boot into main menu. But now im having a weird issue. The window on my desktop shows the main menu, but in vr It's all black screen. Like even if I turn around

**Comment by FWDekker** [comment]
Happy to hear that that issue is resolved!

The black screen issue you mention can be solved by editing the file `vrperfkit.yml` in your `[fo4vr_dir]`, and changing `method: cas` to `method: fsr`.

**Comment by SonikBroom** [comment]
tysm! its fixed!

**Comment by FWDekker** [comment]
No problem! Enjoy the game :-)
