### ISSUE TITLE
Add mention of Steam library setup tool, improvements

### ISSUE THREAD

**Issue by daanvissers** [FWDekker/fo4vr-modlist#25]
Hello! Thank you for writing such an excellent, well-structured and concise guide.

There were a few very minor things I encountered during the whole setup process, which I would like to suggest (I've made a PR for that [here](https://github.com/FWDekker/fo4vr-modlist/pull/26))
- Mention of Steam library setup tool; this can potentially save a lot of time when trying to install FO4VR outside of the `Program Files (x86)` directory, as you won't need to move over or re-download your entire library when someone has only one disk available to install to
- Mention of refreshing the Plugins list in MO2, by refreshing the Data tab. This wasn't obvious to me at first, a bit confusing on MO2's end

Two other suggestions:
- I think this should be possible, but haven't tried it: MO2 has the option to create a desktop shortcut, which can then be added to Steam as a non-Steam game, to be able to quickly launch FO4VR with mods included via the SteamVR interface. 
- I'm not sure if it is relevant for the guide, but maybe mentioning the [Fallout 4 VR Achievements Enabler](https://www.nexusmods.com/fallout4/mods/28556). This might be something that speaks for itself but after playing for a while I remembered that I wanted to earn achievements still, too.

Again, thank you for all these details, playing Fallout 4 in VR like this is an absolute blast!

**Comment by FWDekker** [comment]
Thanks for opening the issue and PR!

I tried the "create a desktop shortcut" two times, and in both cases it botched the launch. (I don't remember the specifics.) I haven't included it in the guide for that reason.

The setup tool sounds intriguing, and I'll take a look at that. I'll have to think over how I want to include it in the guide, since, even if it works on my machine, it may subtly break things in the background for other users.

Unfortunately, I don't currently have much time to consider the issue and PR in detail. I'll (probably) look at it in more detail later this month.

**Comment by fwdekker** [comment]
I've merged #26, which includes your mention of the external library setup tool :-)

I think the only part of your issue I haven't addressed / commented on is the achievements enabler (correct me if I'm wrong!). I looked into it, and apparently enabling achievements with mods is a feature of [Buffout 4 VR](https://www.nexusmods.com/fallout4/mods/64880), which is included in the mod list. (I didn't even know that before looking into it, oops.) I've explicitly mentioned that feature in the guide now, as of commit f24b0abf707bf784ededd5062fe8beffebb49249.

I think that's all, so I'll close this issue. If I've missed something, let me know and/or reopen the issue and/or open a new issue. Thank you for the contributions! (I've added you to the acknowledgements section as well.)
