### ISSUE TITLE
Frik causes CTD when loading save outside vault. No ctd with all other mods enabled, only FRIK causes this.

### ISSUE THREAD

**Issue by lordofwar1379** [FWDekker/fo4vr-modlist#27]
Title. I even tried downloading the newer version of FRIK and it still causes this. everything else works fine, but as soon as I enable FRIK I cant load my save outside the vault. same save loads perfectly fine with all other mods from guide installed. any suggestions?

**Comment by fwdekker** [comment]
To be sure I understand you correctly, you:
1. played through the tutorial and exited the vault, with FRIK disabled the entire time, and then
2. saved the game, exited, enabled FRIK, and started the game again, and finally
3. loaded your save, which resulted in a crash.

Is that correct? I want to be sure, because _if you had FRIK enabled during the tutorial_, the crash was already warned about in the tutorial, and your only solution is to disable FRIK, start a new game, complete the tutorial, and make sure you enable FRIK _only after_  you have exited the vault.

---

If the above does not solve your issue, here's the next troubleshooting tip. (But make sure you triple-check the above.)

Did you enable/disable any mods _during_ the tutorial? For example, did you have FRIK/UFO4P/_any other mod_ enabled when you created your character, then you disabled that mod, continued the tutorial, exited the vault, then saved, enabled FRIK, and got a crash when you loaded?

The tutorial is, unfortunately, a very fragile part of the game. If you enabled/disabled any mods _during_ the tutorial, you'll have to start a new game, while making sure UFO4P and FRIK are disabled the entire time, and keep your mods the same throughout.

---

If neither of the above helped, I think I'll need more information to help you solve your issue. Do you use any mods not listed in this guide? Which mods exactly do you have?

It may help if you give me a list of all your active mods. You can export it from MO2 as follows:
1. In your mod list on the left, right-click on any mod.
2. Choose "All mods", then "Export to csv...".
3. In the window that pops up, select "Only active (checked) mods from your current profile", and enable "Mod_Priority", "Mod_Name", "Mod_Status", "Nexus_ID", and "Mod_Version".
4. Click "OK".
5. Click "Save As..." to save the file somewhere on your computer.
6. Attach the file to a comment on this issue in GitHub.

**Comment by lordofwar1379** [comment]
Hey there!

Frik was enabled only after leaving the elevator in the tutorial. I ended
up figuring out it was because my custom ini was *not* being edited by MO2
because my f4vr was on a different drive. I edited the ini manually and
everything is good now!

Thank you for the quick response though!

**Comment by fwdekker** [comment]
I'm happy to hear that you solved it! Cheers, and have fun!
